# Generated by Django 5.2.14 on 2026-05-30 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='roomimage',
            name='unique_room_cover_image',
        ),
        migrations.AddField(
            model_name='roomimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='roomimage',
            name='moderation_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='roomimage',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomimage',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_room_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roomimage',
            name='source',
            field=models.CharField(choices=[('landlord', 'Landlord'), ('student', 'Student'), ('admin', 'Admin')], default='landlord', max_length=20),
        ),
        migrations.AddField(
            model_name='roomimage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='roomimage',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_room_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='roomimage',
            index=models.Index(fields=['room', 'status', 'source'], name='room_image_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='roomimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_cover', True), ('status', 'approved')), fields=('room',), name='unique_room_cover_image'),
        ),
    ]
