# Generated by Django 5.2.14 on 2026-05-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_roomimage_unique_room_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='gender_policy',
            field=models.CharField(choices=[('any', 'Tất cả'), ('male', 'Nam'), ('female', 'Nữ')], default='any', max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('draft', 'Bản nháp'), ('pending', 'Chờ duyệt'), ('active', 'Đang hiển thị'), ('rejected', 'Bị từ chối'), ('inactive', 'Đã ẩn'), ('rented', 'Đã cho thuê')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='source',
            field=models.CharField(choices=[('landlord', 'Chủ trọ'), ('student', 'Sinh viên'), ('admin', 'Admin')], default='landlord', max_length=20),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Bị từ chối')], default='approved', max_length=20),
        ),
    ]
