# Generated by Django 5.2.15 on 2026-06-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_room_location_geocoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='verification_level',
            field=models.CharField(choices=[('unverified', 'Chưa xác minh'), ('poster_verified', 'Đã xác minh người đăng'), ('room_documents', 'Đã xác minh thông tin phòng'), ('landlord_confirmed', 'Chủ trọ xác nhận'), ('platform_inspected', 'Nền tảng kiểm duyệt')], default='unverified', max_length=30),
        ),
        migrations.AddField(
            model_name='room',
            name='verification_note',
            field=models.TextField(blank=True),
        ),
    ]
