# Generated by Django 5.2.14 on 2026-05-29 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=6, max_digits=8)),
                ('rank', models.PositiveIntegerField()),
                ('score_detail', models.JSONField(blank=True, default=dict)),
                ('was_clicked', models.BooleanField(default=False)),
                ('was_contacted', models.BooleanField(default=False)),
                ('was_favorited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_logs', to='listings.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('rank', '-created_at'),
                'indexes': [models.Index(fields=['user', '-created_at'], name='rec_user_created_idx'), models.Index(fields=['room'], name='rec_room_idx'), models.Index(fields=['score'], name='rec_score_idx')],
            },
        ),
    ]
