# Generated by Django 5.2.14 on 2026-05-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landlordprofile",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("unverified", "Chưa xác thực"),
                    ("pending", "Chờ duyệt"),
                    ("approved", "Đã xác thực"),
                    ("rejected", "Bị từ chối"),
                ],
                default="unverified",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Sinh viên"),
                    ("landlord", "Chủ trọ"),
                    ("admin", "Admin"),
                ],
                default="student",
                max_length=20,
            ),
        ),
    ]
