# Generated by Django 5.2.15 on 2026-06-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_alter_user_groups_and_more'),
        ('locations', '0001_initial'),
        ('roommates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(choices=[('unknown', 'Chưa cập nhật'), ('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='lifestyle_tags',
            field=models.ManyToManyField(blank=True, related_name='student_preferences', to='roommates.lifestyletag'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='move_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='preferred_districts',
            field=models.ManyToManyField(blank=True, related_name='student_preferences', to='locations.district'),
        ),
    ]
