# Generated by Django 5.2.15 on 2026-06-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_studentprofile_gender_studentprofile_lifestyle_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlordprofile',
            name='verification_note',
            field=models.TextField(blank=True),
        ),
    ]
