# Generated by Django 5.2.15 on 2026-06-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmark',
            name='type',
            field=models.CharField(choices=[('university', 'Trường đại học'), ('bus_stop', 'Trạm xe bus'), ('hospital', 'Bệnh viện'), ('park', 'Công viên'), ('shopping_mall', 'Trung tâm thương mại')], max_length=30),
        ),
    ]
