# Generated by Django 5.2.15 on 2026-06-10 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0003_alter_room_gender_policy_alter_room_status_and_more'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LifestyleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(max_length=60, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RoommatePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('has_room', 'Đã có phòng'), ('looking_together', 'Tìm bạn cùng thuê')], max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('active', 'Đang hiển thị'), ('closed', 'Đã đóng'), ('rejected', 'Bị từ chối')], default='draft', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('gender_preference', models.CharField(choices=[('any', 'Không yêu cầu'), ('male', 'Nam'), ('female', 'Nữ'), ('same', 'Cùng giới')], default='any', max_length=10)),
                ('max_roommates', models.PositiveSmallIntegerField(default=1)),
                ('current_occupants', models.PositiveSmallIntegerField(default=0)),
                ('available_slots', models.PositiveSmallIntegerField(default=1)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lifestyle_tags', models.ManyToManyField(blank=True, related_name='roommate_posts', to='roommates.lifestyletag')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roommate_posts', to=settings.AUTH_USER_MODEL)),
                ('preferred_districts', models.ManyToManyField(blank=True, related_name='roommate_posts', to='locations.district')),
                ('room', models.ForeignKey(blank=True, help_text='Optional room when the poster already has a room and needs roommates.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roommate_posts', to='listings.room')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roommate_posts', to='locations.university')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roommate_posts', to='locations.ward')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'type', '-created_at'], name='roommate_status_type_idx'), models.Index(fields=['university', 'status'], name='roommate_university_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('budget_min__isnull', True), ('budget_max__isnull', True), ('budget_min__lte', models.F('budget_max')), _connector='OR'), name='roommate_budget_range_valid'), models.CheckConstraint(condition=models.Q(('budget_min__isnull', True), ('budget_min__gte', 0), _connector='OR'), name='roommate_budget_min_non_negative'), models.CheckConstraint(condition=models.Q(('budget_max__isnull', True), ('budget_max__gte', 0), _connector='OR'), name='roommate_budget_max_non_negative'), models.CheckConstraint(condition=models.Q(('max_roommates__gt', 0)), name='roommate_max_roommates_positive'), models.CheckConstraint(condition=models.Q(('available_slots__gt', 0)), name='roommate_available_slots_positive')],
            },
        ),
    ]
