# Generated by Django 5.2.15 on 2026-06-26 01:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_room_verification_level_room_verification_note'),
        ('locations', '0002_alter_landmark_type'),
        ('roommates', '0002_roommatepost_status_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='roommatepost',
            name='external_room_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='roommatepost',
            name='external_room_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='roommatepost',
            name='external_room_total_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='roommatepost',
            name='room_verification_level',
            field=models.CharField(choices=[('unverified', 'Chưa xác minh'), ('poster_verified', 'Đã xác minh người đăng'), ('room_documents', 'Đã xác minh thông tin phòng'), ('landlord_confirmed', 'Chủ trọ xác nhận'), ('platform_inspected', 'Nền tảng kiểm duyệt')], default='unverified', max_length=30),
        ),
        migrations.AddField(
            model_name='roommatepost',
            name='room_verification_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='roommatepost',
            constraint=models.CheckConstraint(condition=models.Q(('external_room_area__isnull', True), ('external_room_area__gt', 0), _connector='OR'), name='roommate_external_area_positive'),
        ),
        migrations.AddConstraint(
            model_name='roommatepost',
            constraint=models.CheckConstraint(condition=models.Q(('external_room_total_rent__isnull', True), ('external_room_total_rent__gte', 0), _connector='OR'), name='roommate_external_rent_non_negative'),
        ),
    ]
